# Created by github.com/cjee21
# Generated by Google Gemini
# License: MIT

function Get-EfiSignatures {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true, ValueFromPipeline=$true)]
        [string]$FilePath
    )

    # Ensure System.Security is loaded for SignedCms
    Add-Type -AssemblyName System.Security

    if (-not (Test-Path $FilePath)) { 
        Write-Error "File not found: $FilePath"
        return 
    }

    $bytes = [System.IO.File]::ReadAllBytes($FilePath)
    $peOffset = [BitConverter]::ToUInt32($bytes, 0x3C)
    
    # Check Magic Number (starts 24 bytes after PE signature)
    $magic = [BitConverter]::ToUInt16($bytes, $peOffset + 24)
    
    if ($magic -eq 0x20B) {
        # 64-bit (PE32+)
        $secDirOffset = $peOffset + 0xA8
    } elseif ($magic -eq 0x10B) {
        # 32-bit (PE32)
        $secDirOffset = $peOffset + 0x98
    } else {
        Write-Error "Unknown PE format or ROM image."
        return @()
    }

    $certTableAddr = [BitConverter]::ToUInt32($bytes, $secDirOffset)
    $certTableSize = [BitConverter]::ToUInt32($bytes, $secDirOffset + 4)

    if ($certTableAddr -eq 0) { return @() }

    $currentOffset = $certTableAddr
    $endOffset = $certTableAddr + $certTableSize
    $signatureResults = New-Object System.Collections.Generic.List[PSObject]

    $sigIndex = 0
    while ($currentOffset -lt $endOffset) {
        $dwLength = [BitConverter]::ToUInt32($bytes, $currentOffset)
        $wCertType = [BitConverter]::ToUInt16($bytes, $currentOffset + 6)

        if ($wCertType -eq 2) { # WIN_CERT_TYPE_PKCS_SIGNED_DATA
            $certDataSize = $dwLength - 8
            $certBlob = New-Object byte[] $certDataSize
            [Buffer]::BlockCopy($bytes, $currentOffset + 8, $certBlob, 0, $certDataSize)

            try {
                $cms = New-Object System.Security.Cryptography.Pkcs.SignedCms
                $cms.Decode($certBlob)

                # Build the custom object for this specific signature block
                $signatureResults.Add([PSCustomObject]@{
                    SignatureIndex = $sigIndex
                    Signer         = $cms.SignerInfos[0].Certificate # Primary signer for this block
                    Certificates   = $cms.Certificates               # All certs in this block
                    RawData        = $certBlob                       # Raw PKCS7 bytes
                })
                $sigIndex++
            } catch {
                Write-Warning "Failed to decode signature block at offset $currentOffset"
            }
        }
        # Step to next signature (8-byte alignment)
        $currentOffset += ($dwLength + 7) -band -bnot 7
    }

    return $signatureResults
}
